### ISSUE TITLE
LA, USA: cache error

### ISSUE THREAD

**Issue by praging** [covidatlas/coronadatascraper#553]
begins failing 2020-03-11 in backwards chronological order.

`TypeError: $ is not a function
    at Object.0 (coronadatascraper/src/shared/scrapers/USA/LA/index.js:26:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runScrapers (coronadatascraper/src/events/crawler/scrape-data/run-scraper.js:103:38)
    at async generate (coronadatascraper/src/shared/index.js:36:18)
    at async generateTimeseries (coronadatascraper/src/shared/timeseries.js:193:18)`

**Comment by jzohrab** [comment]
If there's no cache hit, the cache returns null, and the get method overall returns null.  The various methods then fail with that weird message `TypeError: $ is not a function`.

My local cache only goes back to 2020-3-12 (that's what's in the repo) ... perhaps the program should just exit if that date is given.

**Comment by lazd** [comment]
This project did not exist until 2020-03-13, so that's why there is no cache.

**Comment by praging** [comment]
maybe I'm misunderstanding. where is the data for that date coming from if there is no cache?

**Comment by jzohrab** [comment]
Perhaps the scrapers are just calling their default URLs they have coded.  I don't think those results would be valid, though.

**Comment by praging** [comment]
closed
